version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  postgres:
    image: postgres
    volumes:
      - ../github-feedback-api/tables:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  tables:
